// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

using System;
using System.Collections.Generic;

namespace DataFlowKit.DbMigrator.Client.SpEntity
{
    /// <summary>
    /// Request model for stored procedure BulkInsertHallAmenities
    /// </summary>
    public class BulkinserthallamenitiesRequestDBO
    {
        /// <summary>Parameter hallId of type bigint</summary>
        public long Hallid { get; set; }

        /// <summary>Parameter vendorId of type bigint</summary>
        public long Vendorid { get; set; }

        /// <summary>Parameter amenityIds of type text</summary>
        public string Amenityids { get; set; }

    }

    /// <summary>
    /// Response model for stored procedure BulkInsertHallAmenities
    /// </summary>
    public class BulkinserthallamenitiesResponseDBO
    {
        /// <summary>Result set #1 from stored procedure BulkInsertHallAmenities</summary>
        public List<BulkinserthallamenitiesResultSet1> ResultSet1 { get; set; } = new List<BulkinserthallamenitiesResultSet1>();

    }

    /// <summary>
    /// Model for result set #1 of stored procedure BulkInsertHallAmenities
    /// </summary>
    public class BulkinserthallamenitiesResultSet1
    {
        /// <summary>Column Id of type INT</summary>
        public int Id { get; set; }

        /// <summary>Column AmenityName of type VARCHAR</summary>
        public string Amenityname { get; set; }

        /// <summary>Column Description of type VARCHAR</summary>
        public string Description { get; set; }

    }

}
